### ISSUE TITLE
No such file or directory - doc/selector_index.html

### ISSUE THREAD

**Issue by vitaliyzolotoy** [tkadauke/css_doc#1]
Hello! After installing CSSDoc I try to use it from command line, but have the following error

/Users/user/Sites/projects/typical/blocks cssdoc popup/popup.css
/Library/Ruby/Gems/1.8/gems/imedo-css_doc-0.0.5/src/css_doc/driver.rb:76:in `initialize': No such file or directory - doc/selector_index.html (Errno::ENOENT)
    from /Library/Ruby/Gems/1.8/gems/imedo-css_doc-0.0.5/src/css_doc/driver.rb:76:in`open'
    from /Library/Ruby/Gems/1.8/gems/imedo-css_doc-0.0.5/src/css_doc/driver.rb:76:in `generate'
    from /Library/Ruby/Gems/1.8/gems/imedo-css_doc-0.0.5/src/css_doc/driver.rb:35:in`generate_index_documentation'
    from /Library/Ruby/Gems/1.8/gems/imedo-css_doc-0.0.5/src/css_doc/driver.rb:9:in `run'
    from /Library/Ruby/Gems/1.8/gems/imedo-css_doc-0.0.5/bin/cssdoc:39:in`run'
    from /Library/Ruby/Gems/1.8/gems/imedo-css_doc-0.0.5/bin/cssdoc:43
    from /usr/bin/cssdoc:19:in `load'
    from /usr/bin/cssdoc:19

**Comment by tkadauke** [comment]
In case you are still interested, I hear this guy had some success with it: https://github.com/rdougan/css_doc
