### ISSUE TITLE
Uninitialized constant CSSDoc::Driver::FileUtils (NameError)

### ISSUE THREAD

**Issue by sam3k** [tkadauke/css_doc#3]
The following error was given after trying to run cssdoc form the example folder given in the repo.

Generating documentation for file buttons.css ...
/Library/Ruby/Gems/1.8/gems/imedo-css_doc-0.0.5/src/css_doc/driver.rb:23:in `generate_file_documentation': uninitialized constant CSSDoc::Driver::FileUtils (NameError)
    from /Library/Ruby/Gems/1.8/gems/imedo-css_doc-0.0.5/src/css_doc/driver.rb:17:in`each'
    from /Library/Ruby/Gems/1.8/gems/imedo-css_doc-0.0.5/src/css_doc/driver.rb:17:in `generate_file_documentation'
    from /Library/Ruby/Gems/1.8/gems/imedo-css_doc-0.0.5/src/css_doc/driver.rb:8:in`run'
    from /Library/Ruby/Gems/1.8/gems/imedo-css_doc-0.0.5/bin/cssdoc:39:in `run'
    from /Library/Ruby/Gems/1.8/gems/imedo-css_doc-0.0.5/bin/cssdoc:43
    from /usr/bin/cssdoc:19:in`load'
    from /usr/bin/cssdoc:19

Operating System: Max OS (Lion).

**Comment by romamatusevich** [comment]
The same problem. 

OS: Windows 7

**Comment by tkadauke** [comment]
In case anyone is still interested in getting this to work, I hear that this guy had some success with it: https://github.com/rdougan/css_doc
